### PR TITLE
Disable onboarding PR

### PR DESCRIPTION
**Pull request by skippednote**

### CODE REVIEW

**Comment by hussainweb** [comment]
@skippednote, from the [documentation](https://docs.renovatebot.com/self-hosted-configuration/#onboarding):

> Set this to false if (a) you configure Renovate entirely on the bot side (i.e. empty renovate.json in repositories) and (b) you wish to run Renovate on every repository the bot has access to, and (c) you wish to skip the onboarding PRs.

We wouldn't be having empty renovate.json in repositories. Will this change cause an impact?

**Comment by skippednote** [comment]
@hussainweb We set it to `false` because
> (c) you wish to skip the onboarding PRs.

**Comment by hussainweb** [comment]
@skippednote, my concern is that the documentation uses the word "and" and not "or". It seems to me that all three conditions should be true. I know that's probably not the case but I'm being cautious.

**Comment by hussainweb** [comment]
@skippednote, with our recent changes in how we run Renovate, I have added renovate.json by default to all projects and config.js is only in the Renovate project now. This PR is not relevant now (nor is the entire `renovate` branch). Closing this.

**Pull request closed without merging**
